spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectdb?serverTimezone=UTC
    username: root
    password: root
    data: classpath:data/data_*.sql
    initialization-mode: never
  jpa:
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: your gmail
    password: your gmail password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  jwtSecret: admin@smarttrack.com
  expirationTime: 864_000_000
  tokenType: JWT
  tokenPrefix: "Bearer "
  tokenHeader: Authorization
  signInUrl: "/login/**"
  manageUsers: "/admin/**"
